openapi: 3.1.0

info:
  title: todo API
  description: TodoアプリのAPIドキュメント
  version: 1.0.0

severs:
  - url: http://localhost:3000/api/v1
    description: Development sever

tags:
  - name: task
    description: タスクに関するエンドポイント

paths:
  /tasks:
    get:
      summary: 全てのタスクを取得
      tags:
        - Task
      responses:
        "200":
          description: OK
          schema:
            type: array
            items:
              type: object
              properties:
                id:
                  type: integer
                title:
                  type: string
                content:
                  type: string
                created_at:
                  type: date-time
                update_at:
                  type: date-time
            example:
              - id: 1
                title: 新規タスクの作成
                content: 新規タスクを作成する
                created_at: 2025/2/1
                update_at: 2025/2/1
    post:
      summary: タスクの新規作成
      tags:
        - Task
      responses:
        "201":
          description: OK
          schema:
            type: object
            properties:
              id:
                type: number
              title:
                type: string
              content:
                type: string
              created_at:
                type: number
              update_at:
                type: number
        "500":
          description: サーバー側の処理で問題が発生した
        "502":
          description: 意図しないパラメータがリクエストされた

  tasks/:id:
    get:
      summary: タスクの詳細を取得
      tags:
        - Task
      parameters:
        - name: postId
          in: path
          required: true
          type: string
      responses:
        "200":
          description: OK
          schema:
            type: object
            properties:
              id:
                type: number
              title:
                type: string
              content:
                type: string
              created_at:
                type: number
              update_at:
                type: number
            example:
              - id: 1
                title: 新規タスクの作成
                content: 新規タスクを作成する
                created_at: 2025/2/1
                update_at: -
        "500":
          description: サーバー側の処理で問題が発生した
        "502":
          description: 意図しないパラメータがリクエストされた
    put:
      summary: 各タスクの内容を更新
      tags:
        - Task
      parameters:
        - name: postId
          in: path
          required: true
          type: string
      responses:
        "200":
          description: 一つのタスクを更新する
          schema:
            type: object
        "500":
          description: サーバー側の処理で問題が発生した
        "502":
          description: 意図しないパラメータがリクエストされた
    delete:
      summary: 各タスクを削除
      tags:
        - Task
      parameters:
        - name: postId
          in: path
          required: true
          type: string
      responses:
        "200":
          description: 一つのタスクを削除する
        "500":
          description: サーバー側の処理で問題が発生した
        "502":
          description: 意図しないパラメータがリクエストされた